### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by gaetandezeiraud** [tay1orjones/hyper-clean#1]
Hello, 
I installed the theme on Hyper but it does not work. I'm on Windows 10 Update creators. Hyper 1.3.2.
The color of the font to change and I have blue rectangle for the cursor but nothing more.

Thank you for your reply.

**Comment by tay1orjones** [comment]
Hyper currently [does not support Vibrancy or transparency on windows](https://github.com/zeit/hyper/issues/1638). Both of which the theme currently uses.

The background color/transparency is set via the theme with `rgba()`, which is causing it to set to your local default rather that the color specified in the theme.

All the other colors are set via hex codes, and should work though. 

Are you getting any other install/load errors, or errors within the devtools console?

An interim fix while waiting for Hyper to fix could probably be a function to set background color, checking the OS and using hex codes if on windows. 

To get a similar look and feel In the meantime, update your default config to set background color to `#1B2834`, the base color of the background.

**Comment by Jnoack331** [comment]
@Brouilles you can use my non transparent fork for the moment.
I hope that works for you.

**Comment by tay1orjones** [comment]
Closing in favor of broader scope fix, #7

**Comment by vyas0189** [comment]
How do I get this on the terminal:
![capture](https://user-images.githubusercontent.com/25915724/41072593-716ba0a6-69c4-11e8-961d-23e85e441343.PNG)

**Comment by tay1orjones** [comment]
@vyas0189 [please see the readme](https://github.com/tay1orjones/hyper-clean#related) regarding the `.bash_prompt`
