### ISSUE TITLE
Cool arrow-style prompt not showing

### ISSUE THREAD

**Issue by pietromarchesi** [tay1orjones/hyper-clean#6]
Hi, 

I have the `hyper-clean` theme in my plugins list, and I get the right color scheme, but the prompt does not look nearly as awesome as the one shown in the screenshot (in fact, it doesn't change). Do you happen to know why that could be? I'm completely new to Hyper, so apologies if this is a naive question. 

Cheers, 

Pietro

**Comment by tay1orjones** [comment]
Hi Pietro! 👋 
You'll need to customize your `.bash_prompt` to style the prompt. I've uploaded mine in [my dotfiles repo](https://github.com/tay1orjones/dotfiles/tree/master/shell), although a word of caution that I've found some bugs with it and haven't had time to fix them. The arrows in particular are [powerline unicode characters](https://github.com/powerline/fonts).

I highly recommend checking out the [awesome curated list of dotfiles resources](https://github.com/webpro/awesome-dotfiles) to find more battle-tested bash profile customizations. [Mathias Bynens repo](https://github.com/mathiasbynens/dotfiles) in particular is a great resource.
