### ISSUE TITLE
Rogue char & carriage return when hyper is launched

### ISSUE THREAD

**Issue by sukisogreat** [tay1orjones/hyper-clean#9]
Probably not an issue with the theme but any help would be appreciated....

When I launch hyper, a white block character and a carriage return is displayed before the prompt. Any way to get rid of this?

<img width="639" alt="Screenshot 2020-03-10 at 10 25 59" src="https://user-images.githubusercontent.com/62014088/76304617-9798c780-62bb-11ea-8316-d119ee1813e7.png">

**Comment by tay1orjones** [comment]
Is this only present when you use the theme? 

It looks like this might be an issue with your bash prompt, likely defined in your `bash_profile` or sourced in your `.bashrc`. I'd be surprised if it's related directly to the theme.

That said, if you post your bash profile source or a link to dotfiles I can lend a hand to see what might be causing it!

**Comment by sukisogreat** [comment]
Yeah its a weird one! I don't notice it when I use the built-in Mac terminal. Funnily enough, I accidentally deleted '.hyper.js' and the character turned into a percent symbol.

I can't find 'bash_profile', am I looking in the wrong place?

<img width="743" alt="Screenshot 2020-03-11 at 12 27 27" src="https://user-images.githubusercontent.com/62014088/76417864-8fad5600-6395-11ea-90c0-0df525ec9e2e.png">
<img width="873" alt="Screenshot 2020-03-11 at 12 27 37" src="https://user-images.githubusercontent.com/62014088/76417931-af447e80-6395-11ea-9e64-e000d6c93d1c.png">


[zshrc.txt](https://github.com/tay1orjones/hyper-clean/files/4318280/zshrc.txt)
[hyper.js.txt](https://github.com/tay1orjones/hyper-clean/files/4318281/hyper.js.txt)

**Comment by sukisogreat** [comment]
Looks like its a bug with hyper, see https://github.com/zeit/hyper/issues/2144

**Comment by tay1orjones** [comment]
Interesting! I'm glad you figured it out. Let me know how the theme works for you and if there's any improvements you'd like to see.
